language: java

jdk: 
 - oraclejdk8

install: 
 - "./gradlew clean jar"
 
env: 
 - COVERAGE=0.35

echo `testing coming soon`

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

before _deploy:
  - COVERAGE=$COVERAGE ./gradlew test jacocoTestCoverageVerification

deploy:
 - provider: script
   script: echo "WIP"
