language: java

jdk: 
 - oraclejdk8

install: 
 - "./gradlew clean jar"


echo `testing coming soon`

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
